// src/app/view-image/[imageId]/page.tsx
// This file is now a Server Component.

import ViewImageClient from './view-image-client';

export async function generateMetadata({ params }: { params: { imageId: string } }) {
  // In a real app, you might fetch metadata based on the imageId
  // For now, we'll use a generic title
  const imageId = decodeURIComponent(params.imageId);
  return {
    title: `View Image: ${imageId.substring(0,20)}... - Imaginarium`,
    description: `Viewing image generated by Imaginarium with ID ${imageId}`,
  };
}

export default function ViewImagePage({ params }: { params: { imageId: string } }) {
  return <ViewImageClient params={params} />;
}
